name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
        env:
          RUSTUP_TOOLCHAIN: nightly
      - name: Security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RUSTUP_TOOLCHAIN: nightly
